[build]
target = "aarch64-virt.json"
rustflags = ["-C", "link-arg=-Tlinker.ld"]

[target.aarch64-virt]
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a53 -nographic -kernel"

[unstable]
build-std = ["core", "alloc"]
